NuoUgnesParduotuve/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NuoUgnesParduotuve/mysite/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.shop, name='shop'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('shipping/', views.shipping, name='shipping'),
    path('payment/', views.payment, name='payment'),
    path('processorder/', views.processOrder, name='processorder'),
    path('orders/', views.UserOrdersListView.as_view(), name='orders'),
    path('orders/<int:pk>', views.orderdetail, name='order_detail'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
    path('<int:pk>', views.productdetail, name='product-detail'),
]

NuoUgnesParduotuve/mysite/shop/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    surname = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')


class Product(models.Model):
    name = models.CharField(_('Name'), max_length=150)
    price = models.IntegerField(_('Price'))
    description = models.TextField(_('Description'), null=True, blank=True)
    cover = models.ImageField(_('Cover'), upload_to='covers', null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    CATEGORY_CHOICES = (
        ('1', _('Kita')),
        ('2', _('Auskarai')),
        ('3', _('Apyrankės')),
        ('4', _('Sagės')),
        ('5', _('Kaklo papuošalai')),
        ('6', _('Aksesuarai')),
        ('7', _('Dovanų kuponai')),
        ('8', _('Kalėdiniai vainikai')),
    )


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    delivery = models.BooleanField(default=False)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=30, null=True, blank=True)

    ORDER_STATUS = (
        ('p', _('Pending')),
        ('a', _('Approved')),
        ('c', _('Cancelled')),
        ('d', _('Completed')),
    )

    status = models.CharField(
    max_length=1,
    choices=ORDER_STATUS,
    blank=True,
    default='p',
    help_text=_('Status'),
    )

    def __str__(self):
        return str(self.id)

    def total(self):
        sum_total = 0
        lines = self.lines.all()
        for line in lines:
            sum_total += line.sum()
        return sum_total

    def total_qty(self):
        total_qty = 0
        lines = self.lines.all()
        for line in lines:
            total_qty += line.quantity
        return total_qty


    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')
        ordering = ['-id']

class OrderLine(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True, related_name='lines')
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def sum(self):
        total = self.product.price * self.quantity
        return total

    class Meta:
        verbose_name = _('Order Line')
        verbose_name_plural = _('Order Lines')

    def __str__(self):
        return f"{self.product}, {self.order}, {self.quantity}"


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(_('Address'), max_length=150, null=True)
    city = models.CharField(_('City'), max_length=150, null=True)
    zip_code = models.CharField(_('Zip Code'), max_length=150, null=True)
    telephone = models.CharField(_('Telephone number'), max_length=20, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    country = models.CharField(_('Country'), max_length=30, null=True)

    def __str__(self):
        return f"{self.customer}, {self.order}, {self.address}"

    class Meta:
        verbose_name = _('ShippingAddress')
        verbose_name_plural = _('ShippingAddresses')

NuoUgnesParduotuve/mysite/shop/views.py
import datetime

from django.shortcuts import render, redirect
from .models import *
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _



# Create your views here.
def shop(request):

    categories = Category.objects.all()     #navigacija pagal kategorijas
    category_id = request.GET.get('category')
    if category_id:
        products = Product.objects.filter(category=category_id)
    else:
        products = Product.objects.all()
    context = {'products': products, 'categories': categories}

    if request.method == 'POST':        #produtų pridėjimas į krepšelį
        product = request.POST.get('product')
        if request.user.is_authenticated:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            if order.lines.filter(product=product).exists():
                eilute = order.lines.get(product=product)
                eilute.quantity += 1
                eilute.save()
            else:
                nauja_preke = order.lines.create(product_id=product, quantity=1)
                nauja_preke.save()
            messages.info(request, _("%s successfully added to the Cart!") % products[int(product)-1])
        else:
            return redirect('login')


    return render(request, 'shop.html', context)


def cart(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.lines.all()
        order.delivery = False  # jei prieš apmokėjimą persigalvotų dėl pristatymo ir grįžtų į krepšelį
        order.save()

        context = {'items': items,
               'order': order
               }

    else:
        return redirect('login')

    if request.method == "POST":
        quantity = request.POST.get('quantity')
        product = request.POST.get('update')
        product_remove = request.POST.get('remove')
        if product_remove:
            OrderLine.objects.filter(order_id=order, product_id=product_remove).delete()
            messages.info(request, _(f"Successfully removed from the Cart!"))
        else:
            if int(quantity) < 1:
                OrderLine.objects.filter(order_id=order, product_id=product).delete()
                messages.info(request, _(f"Successfully removed from the Cart!"))
            else:
                new_quantity = order.lines.get(product=product)
                new_quantity.quantity = quantity
                new_quantity.save()
                messages.info(request, _(f"Quantity successfully updated!"))


    return render(request, 'cart.html', context)


def checkout(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.lines.all()
        context = {'items': items,
                    'order': order
               }
    else:
        return redirect('login')



    return render(request, 'checkout.html', context)

def shipping(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        delivery = order.total() + 5  #pristatymo išlaidos
        items = order.lines.all()
        context = {'items': items,
            'order': order,
            'delivery': delivery
            }

        if request.method == "POST":
            customer = request.user.customer
            address = request.POST['address']
            city = request.POST['city']
            zipcode = request.POST['zipcode']
            country = request.POST['country']
            number = request.POST['number']
            order.delivery = True
            order.save()
            ShippingAddress.objects.create(customer_id=customer.id, order_id=order.id, address=address, city=city, zip_code=zipcode, country=country, telephone=number)
            return redirect('payment')

        return render(request, 'shipping.html', context)

def payment(request):                   #   sb-3cp1e25263800@personal.example.com  sb-tdduk25263796@business.example.com
                                        #   Ytfd4>"-                               ecW8a8/F
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        delivery = order.total() + 5
        items = order.lines.all()
    else:
        items = []
        delivery = 0
        order = {'total': 0, 'total_qty': 0}

    context = {'items': items,
               'order': order,
               'delivery': delivery
               }

    return render(request, 'payment.html', context)


@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        name = request.POST['name']
        surname = request.POST['surname']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, _('Username %s already exist!') % username)
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, _('Email %s already exists!') % email)
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    user = User.objects.create_user(username=username, email=email, password=password)
                    Customer.objects.create(user=user, email=email, name=name, surname=surname)
                    messages.info(request, _('User %s successfully registered!') % username)
                    return redirect('login')
        else:
            messages.error(request, _('Passwords do not match!'))
            return redirect('register')
    return render(request, 'registration/register.html')


def search(request):
    query = request.GET.get('query')
    search_results = Product.objects.filter(Q(name__icontains=query))
    return render(request, 'search.html', {'products': search_results, 'query': query})


def productdetail(request, pk):
    context = {}
    context['product'] = Product.objects.get(id=pk)

    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        if request.user.is_authenticated:
            customer = request.user.customer
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            if order.lines.filter(product_id=pk).exists():
                eilute = order.lines.get(product_id=pk)
                eilute.quantity = eilute.quantity + int(quantity)
                eilute.save()
            else:
                nauja_preke = order.lines.create(product_id=pk, quantity=quantity)
                nauja_preke.save()
        messages.info(request, _(f"Successfully added to the Cart!"))

    return render(request, 'product_detail.html', context=context)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    customer = request.user.customer
    order = Order.objects.get(customer=customer, complete=False)
    order.transaction_id = transaction_id
    order.complete = True
    order.status = 'a'
    order.save()

    context = {
        'order': order
    }

    return render(request, 'processorder.html', context)


class UserOrdersListView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'orders.html'

    def get_queryset(self):
        return Order.objects.filter(customer=self.request.user.customer, complete=True)

def orderdetail(request, pk):

    if request.user.is_authenticated:
        customer = request.user.customer
        order = Order.objects.get(id=pk, customer=customer)
        items = order.lines.all()
    else:
        items = []
        order = {'total': 0, 'total_qty': 0}

    context = {'items': items,
                'order': order,
                   }

    return render(request, 'order_detail.html', context=context)

NuoUgnesParduotuve/mysite/shop/templates/base.html
<!DOCTYPE html>
<html lang="lt">
<head>
	<link rel="shortcut icon" type="image/png" href="img/favicon.png">
  {% block title %}{% endblock %}
	<link rel="icon" type="image/x-icon" href="https://static.thenounproject.com/png/1920692-200.png">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
{% load static %}

<div class="p-1 bg-white text-white text-center bg-opacity-75">

  <img src="{% static 'img/logo.png' %}" height="200" width="200" alt="nuo UGNES" title="nuo UGNES">

		  <a href="https://www.instagram.com/nuo_ugnes/">
			  <img src="{% static 'img/ig.png' %}" style="width:39px; height:39px; margin-top:7px" class="float-end"></a>

	<a href="https://www.facebook.com/profile.php?id=100063006373249">
			  <img src="{% static 'img/fb.png' %}" style="width:53px; height:53px;" class="float-end"></a>
 <div class="form-group row">
	<div class="col-sm-8"></div>
     <div class="col-sm-2">
         <div class="text-end" style="margin-top:10px">
        {% load i18n %}
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}"/>
        <select name="language" onchange="this.form.submit()">
          {% load static %}
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
            {{ lang.1 }}
          </option>
          {% endfor %}
        </select>
      </form>
    </div>
     </div>
	<div class="col-sm-2">
	<form action="{% url 'search' %}" method="get" class="float-bottom">
    <input name="query" class="form-control" type="text" placeholder="Paiešką">
    </form>
</div>
 </div>
</div>

	<nav class="navbar navbar-expand-lg navbar-dark" style="background:#404040">
	  <a class="navbar-brand" href="{% url 'shop' %}">
		  <img src="{% static 'img/whitelogo.png' %}" height="50" width="50" style="margin-left:15px;" >
	  </a>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'shop' %}"><strong>{% trans "Shop" %}</strong></a>
		  </li>
	    </ul>

		  <ul class="navbar-nav ms-auto">
      {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link">{% trans "You are connected:" %} <b>{{ user.get_username }}</b></a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'orders' %}">{% trans "Order history" %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">{% trans "Login" %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'register'%}?next={{request.path}}">{% trans "Register" %}</a></li>
          {% endif %}
</ul>
	     	<a class="nav-link" href="{% url 'cart' %}">
	    		<img  id="cart-icon" src="{% static 'img/cart2.png' %}" style="margin-right:15px;">

<!--				<p id="cart-total">0</p></a>-->

            </a>
      </div>
	</nav>

     <div class="container">
            <br>
         {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                {{ message }}
        </div>
    {% endfor %}
{% endif %}
            {% block content %}


            {% endblock content %}
         </div>

<footer class="bg-dark fixed-bottom">
    <p class="text-white" style="font-size: 12px; text-align:center"> {% trans "2023 E-Commerce Website by Mindaugas Pupienis. All rights reserved." %}</p>
</footer>

</body>
</html>

NuoUgnesParduotuve/mysite/shop/templates/cart.html
{% extends "base.html" %}
{% load i18n %}
  {% block title %}<title>{% trans 'Cart' %}</title>{% endblock %}
{% block content %}
{% load static %}

<div class="row">
        <br>
    <div class="col-lg-9">
        <div class="box-element">
        <div class="cart-row">
            <div style="flex:1"></div>
             <div style="flex:1"><strong>{% trans 'Item'%}</strong></div>
             <div style="flex:1"><strong>{% trans 'Price' %}</strong></div>
             <div style="flex:2"><strong>{% trans 'Quantity' %}</strong></div>
             <div style="flex:1"><strong>{% trans 'Total'%}</strong></div>
        </div>
            {% for item in items %}
             <div class="cart-row">
            <div style="flex:1"><img class="row-image" src="{{item.product.cover.url}}"></div>
             <div style="flex:1">{{item.product.name}}</div>
             <div style="flex:1">{{item.product.price}}</div>
             <div style="flex:2">
                <div class="row">
                    <div class="col-lg-4">
                 <form method="post">
                    <div class="col-lg-12">

                    {% csrf_token %}
                    <div class="mb-2">
                        <input type="number" class="form-control" value="{{item.quantity}}" name="quantity">
                    </div>
                     </div>

                     <div class="col-lg-6">
                        <div class="form-group">
                            <input hidden type="text" value="{{item.product.id}}" name="update">
                            <button type="submit" class="btn btn-outline-secondary">{% trans 'Update' %}</button>
                        </div>
                        </div>
                    </form>
                    </div>

                    <div class="col-lg-4">
                        <div class="col-lg-6" style="margin-top:58px"></div>
                    <div class="col-lg-6">
                        <form method = "POST">
                            {% csrf_token %}
                         <div class="form-group" style="margin-top:10px;">
                             <input hidden type="text" value="{{item.product.id}}" name="remove">
                            <button type="submit" class="btn btn-outline-danger">{% trans 'Remove' %}</button>
                        </div>
                        </form>
                    </div>
                    </div>

</div>
                </div>



             <div style="flex:1">€{{item.sum}}</div>
        </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-lg-3">
        <div class="box-element" style="height:220px">
            <a class="btn btn-outline-dark" href="{% url 'shop' %}">&#x2190; {% trans 'Continue Shopping' %}</a>
            <br>
	        <br>

			<h5>Items: <strong>{{order.total_qty}}</strong></h5>
            <br>
			<h5>Total:<strong> €{{order.total}}</strong></h5>

                {% if order.total_qty > 0 %}
				<a  style="float:right; margin:5px; width:100%;" class="btn btn-success" href="{% url 'checkout' %}">{% trans 'Checkout' %}</a>
                {% endif %}
            </div>
    </div>
</div>
{% endblock content %}

NuoUgnesParduotuve/mysite/shop/templates/checkout.html
{% extends "base.html" %}
{% load i18n %}
  {% block title %}<title>{% trans 'Checkout' %}</title>{% endblock %}
{% block content %}
{% load static %}

  <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">

					<br>

					<div class="row">
						<div class="col-lg-9">
							<p>{% trans 'Courier delivery' %} <b>(+€ 5)</b></p>
						</div>
						<div class="col-lg-2">
							<a class="btn btn-success btn-block" href="{% url 'shipping' %}" name="delivery">{% trans 'Choose' %}</a>
						</div>
					</div>
					<br>
					<div class="row">
						<div class="col-lg-9">
							<p>{% trans 'Pick up in place' %} (+€0)</p>
						</div>
						<div class="col-lg-2">
							<a class="btn btn-success btn-block" href="{% url 'payment' %}" name="pickup">{% trans 'Choose' %}</a>
						</div>
					</div>
				<br>

			</div>



		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; {% trans 'Back to Cart' %}</a>
				<hr>
				<h3>{% trans 'Order Summary' %}</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.cover.url}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>€{{item.product.price}}</p></div>
					<div style="flex:1"><p>{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>{% trans 'Items:' %}   {{order.total_qty}}</h5>
				<h5>{% trans 'Total:' %}   €{{order.total}}</h5>
			</div>

		</div>

	</div>

{% endblock content %}

NuoUgnesParduotuve/mysite/shop/templates/order_detail.html
{% extends "base.html" %}
{% load i18n %}
  {% block title %}<title>{% trans 'Order detail' %}</title>{% endblock %}
{% block content %}
{% load static %}

<h2>{% trans 'Products ordered:' %}</h2>
<div class="row">
        <br>
    <div class="col-lg-9">
        <div class="box-element">
        <div class="cart-row">
            <div style="flex:1"></div>
             <div style="flex:1"><strong>{% trans 'Item' %}</strong></div>
             <div style="flex:1"><strong>{% trans 'Price' %}</strong></div>
             <div style="flex:2"><strong>{% trans 'Quantity' %}</strong></div>
             <div style="flex:1"><strong>{% trans 'Total' %}</strong></div>
        </div>

            {% for item in items %}
             <div class="cart-row">
            <div style="flex:1"><img class="row-image" src="{{item.product.cover.url}}"></div>
             <div style="flex:1">{{item.product.name}}</div>
             <div style="flex:1">{{item.product.price}}</div>
             <div style="flex:2">{{item.quantity}}</div>
             <div style="flex:1">€{{item.sum}}</div>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="col-lg-3">
        <div class="box-element" style="height:220px">
            <a class="btn btn-outline-dark" href="{% url 'orders' %}">&#x2190; {% trans 'Back to my orders' %}</a>
            <br>
	        <br>

			<h5>Items: <strong>{{order.total_qty}}</strong></h5>
            <br>
			<h5>Total:<strong> €{{order.total}}</strong></h5>
            </div>
    </div>
</div>
{% endblock %}

NuoUgnesParduotuve/mysite/shop/templates/orders.html
{% extends "base.html" %}
{% load i18n %}
  {% block title %}<title>{% trans 'Your orders history' %}</title>{% endblock %}
{% block content %}
{% load static %}

<h2>{% trans 'Your orders' %}</h2>
<table class="table table-striped table-bordered">
            <tbody><tr>
                <th>{% trans 'Order number' %}</th>
                <th>{% trans 'Num items' %}</th>
                <th>{% trans 'Total inc tax' %}, €</th>
                <th>{% trans 'Date submitted' %}</th>
                <th>{% trans 'Status' %}</th>
            </tr>
            {% for order in order_list %}
                <tr>
                    <td><a href="{% url 'order_detail' order.id %}">{{order.id}}</a></td>
                    <td>{{order.total_qty}}</td>
                    <td>{{order.total}}</td>
                    <td>{{order.date_ordered}}</td>
                    <td>{{order.get_status_display}}</td>
                </tr>
            {% endfor %}

        </tbody></table>

{% endblock %}

NuoUgnesParduotuve/mysite/shop/templates/payment.html
{% extends "base.html" %}
{% load i18n %}
  {% block title %}<title>{% trans 'Payment' %}</title>{% endblock %}
{% block content %}
{% load static %}

  <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">

					<br>
	<div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AYwhU9OyV6Gak91N8A52fCxkZwYaiRJ1yEPNwEIsSuWCws-Yz23zbQIdfi5EVBCP2qXrtFhGhX35A7KY&currency=EUR&locale=en_LT"></script>

    <script>

    if ('{{order.delivery}}') {
    	var total = '{{order.total}}'
    } else {
    	var total = '{{delivery}}'
    }


       paypal.Buttons({

            // Call your server to set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                purchase_units: [{
                        amount: {
                            value:parseFloat(total)
                        }
                    }]
                });
            },

            // Call your server to finalize the transaction
            onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
            submitFormData()
            });
		}
        }).render('#paypal-button-container');
    </script>
	<script>
		function submitFormData(){
		console.log('Payment button clicked')
		window.location.href = "{% url 'processorder' %}"
		}
	</script>
			</div>



		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; {% trans 'Back to Cart' %}</a>
				<hr>
				<h3>{% trans 'Order Summary' %}</h3>
				<h5>{% trans 'Items:' %}   {{order.total_qty}}</h5>
				{% if order.delivery %}
				<h5>{% trans 'Total:' %}   €{{delivery}}</h5>
				{% else %}
				<h5>{% trans 'Total:' %}   €{{order.total}}</h5>
				{% endif %}
			</div>

		</div>

	</div>

{% endblock content %}

NuoUgnesParduotuve/mysite/shop/templates/processorder.html
{% extends "base.html" %}
{% load i18n %}
  {% block title %}<title>{% trans 'Success!' %}</title>{% endblock %}
{% block content %}
{% load static %}
<div class="box-element pt-2">
    <div class="p-2 m-2">
        <div class="col-md-8 mx-auto pt-3">
            <h3 class="text-center pb-2">{% trans 'We successfully received your payment. Your order' %} <b><u>{% trans 'No.' %} {{order}}</u></b> {% trans 'will be sent / be ready to pick up in few days.' %}</h3>
            <br>
                <div class="row">
                    <div class="col-lg-2"></div>
                    <div class="col-lg-5">
                <a  class="btn btn-success" href="{% url 'shop' %}">{% trans 'To the Shop' %}</a>
                    </div>
                     <div class="col-lg-5">
                <a  class="btn btn-warning" href="{% url 'orders' %}">{% trans 'Your orders history' %}</a>
                     </div>
                </div>
        </div>
    </div>
</div>








{% endblock %}