TODOlist/mysite/todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('manouzduotys/', views.UzduotysListView.as_view(), name='manouzduotys'),
    path('manouzduotys/nauja/', views.UserUzduotisCreateView.as_view(), name='nauja'),
    path('manouzduotys/<int:pk>/update', views.UzduotisUpdateView.as_view(), name='redaguoti'),
    path('manouzduotys/<int:pk>/delete', views.UzduotisDeleteView.as_view(), name='istrinti'),
]

TODOlist/mysite/todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Uzduotis(models.Model):
    uzduotis = models.CharField('Užduotis', max_length=200)
    vartotojas = models.ForeignKey(User, on_delete=models.CASCADE)
    data = models.DateTimeField('Data', auto_now_add=True)

    def __str__(self):
        return f"{self.vartotojas} \nužduotis: {self.uzduotis} \n({self.data})"

    class Meta:
        verbose_name = 'Užduotis'
        verbose_name_plural = 'Užduotys'

TODOlist/mysite/todo/forms.py
from .models import Uzduotis
from django import forms


# class UserUzduotisCreateForm(forms.ModelForm):
#     class Meta:
#         model = Uzduotis
#         fields = ['uzduotis', 'vartotojas']
#         widgets = {'vartotojas': forms.HiddenInput()}

TODOlist/mysite/todo/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Uzduotis

# Create your views here.
def index(request):
    return render(request, 'index.html')


class UzduotysListView(LoginRequiredMixin, generic.ListView):
    model = Uzduotis
    template_name = 'manouzduotys.html'
    paginate_by = 4

    def get_queryset(self):
        return Uzduotis.objects.filter(vartotojas=self.request.user)


class UserUzduotisCreateView(LoginRequiredMixin, generic.CreateView):
    model = Uzduotis
    fields = ['uzduotis']
    success_url = '/todo/manouzduotys'
    template_name = 'user_uzduotis_form.html'

    def form_valid(self, form):
        form.instance.vartotojas = self.request.user
        return super().form_valid(form)


class UzduotisUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Uzduotis
    fields = ['uzduotis']
    success_url = '/todo/manouzduotys'
    template_name = 'user_uzduotis_form.html'

    def form_valid(self, form):
        form.instance.vartotojas = self.request.user
        return super().form_valid(form)


class UzduotisDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Uzduotis
    success_url = '/todo/manouzduotys'
    template_name = 'trinimas_form.html'

    def form_valid(self, form):
        form.vartotojas = self.request.user
        return super().form_valid(form)

TODOlist/mysite/todo/templates/base.html
<!DOCTYPE html>
<html lang="lt">
<head>
  {% block title %}{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="p-1 bg-primary text-white text-center">
  <h3>
  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-card-checklist" viewBox="0 0 16 16">
  <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
  <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z"/>
</svg>
  Mano užduotys
  </h3>
  <p>Užduočių planavimo programa (TODO list)</p>
</div>


<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'index' %}">Pradžia</a>
      </li>
      {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="{% url 'nauja' %}">Sukurti</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'manouzduotys' %}">Mano užduotys</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}?next={{request.path}}">Atsijungti</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>

          {% endif %}
    </ul>
    <ul class="navbar-nav ms-auto">
      {% if user.is_authenticated %}
          <li></li><li class="nav-item"><a class="nav-link" href="#">Esate prisijungę kaip: <b>{{ user.get_username }}</b></a></li>
           {% endif %}
    </ul>

  </div>
</nav>

<br/>
<div>
      {% block content %}{% endblock %}
    </div>

<div class="footer-fluid bg-dark text-white text-end fixed-bottom">
  <p>©2023 Mindaugas Pupienis</p>
</div>

</body>
</html>

TODOlist/mysite/todo/templates/index.html
{% extends "base.html" %}
{% block title %}<title>TODO list</title>{% endblock %}
{% block content %}
<h2>Sveiki atvykę!</h2>
{% endblock content %}

TODOlist/mysite/todo/templates/manouzduotys.html
{% extends "base.html" %}
{% block title %}<title>Mano užduotys</title>{% endblock %}
{% block content %}

    {% if uzduotis_list %}
    <ul>

      {% for uzduotis in uzduotis_list %}
        <li>
        {{ uzduotis }}
            <br>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'redaguoti' uzduotis.id %}">Redaguoti</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'istrinti' uzduotis.id %}">Ištrinti</a>
          <hr>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Šiuo metu užduočių neturite.</p>
    {% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

TODOlist/mysite/todo/templates/trinimas_form.html
{% extends "base.html" %}
{% block title %}<title>Trinimas</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti užduotį</legend>
            <p>Ar tikrai norite ištrinti užduotį {{ uzduotis }}?</p>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'manouzduotys' %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

TODOlist/mysite/todo/templates/user_uzduotis_form.html
{% extends "base.html" %}
{% block title %}<title>Užduoties sukūrimas/redagavimas</title>{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Užduoties sukūrimas/redagavimas</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
    </div>
{% endblock content %}